/**
 * String constants for the application
 * Centralized for easy internationalization and maintenance
 */

export const Strings = {
  app: {
    name: 'Peyo Pagos',
  },
  common: {
    loading: 'Cargando datos...',
    next: 'Siguiente',
    skip: 'Omitir',
    start: 'Empezar',
    login: 'Iniciar sesión',
    register: 'Registrarse',
    submit: 'Enviar',
    cancel: 'Cancelar',
    save: 'Guardar',
    delete: 'Eliminar',
    error: 'Error',
    success: 'Éxito',
    continue: 'Continuar',
    confirm: 'Confirmar',
    resend: 'Reenviar',
  },
  welcome: {
    title: '¡Bienvenido a Peyo!',
    subtitle: 'Descubre el futuro de la gestión financiera rápida y sencilla.',
  },
  onboarding: {
    screens: [
      {
        title: 'Bienvenido a Peyo Pagos',
        subtitle: 'Tu gateway crypto-fiat para finanzas globales',
        buttonText: 'Empezar',
      },
      {
        title: 'Pagos sin limites',
        subtitle: 'Envía dinero a cualquier país y transfiere crypto entre wallets al instante',
        buttonText: 'Conocer más',
      },
      {
        title: 'Tu Tarjeta Peyo Pagos',
        subtitle: 'Gasta tu crypto en cualquier tienda como si fuera dinero tradicional',
        buttonText: 'Conocer más',
      },
      {
        title: 'Recibe Pagos Fácil',
        subtitle: 'Recibe pagos con enlaces y QR, además de notificaciones de cada movimiento',
        buttonText: 'Comenzar',
      },
    ],
  },
  auth: {
    login: {
      title: 'Bienvenido de nuevo',
      subtitle: 'Inicia sesión en tu cuenta',
      emailPlaceholder: 'Correo electrónico',
      passwordPlaceholder: 'Contraseña',
      forgotPassword: '¿Olvidaste tu contraseña?',
      noAccount: '¿No tienes cuenta?',
      registerAction: 'Regístrate',
      loginButton: 'Iniciar sesión',
      loginWithGoogle: 'Iniciar sesión con Google',
    },
    register: {
      title: 'Regístrate ahora',
      subtitle: 'Comienza tu viaje hoy',
      emailPlaceholder: 'Correo electrónico',
      phonePlaceholder: 'Celular',
      firstNamePlaceholder: 'Nombre',
      lastNamePlaceholder: 'Apellido',
      passwordPlaceholder: 'Contraseña',
      confirmPasswordPlaceholder: 'Confirmar contraseña',
      hasAccount: '¿Ya tienes cuenta?',
      loginAction: 'Iniciar sesión',
      registerButton: 'Registrarse',
      registerWithGoogle: 'Regístrate con Google',
      avatarTitle: 'Foto de perfil',
      avatarText: 'Opcional',
      termsText: 'Acepto los',
      termsLink: 'Términos y Condiciones',
      privacyLink: 'Política de Privacidad',
    },
    otp: {
      title: 'Verifica tu cuenta',
      subtitle: 'Por favor ingresa el código de 4 dígitos que te enviamos a',
      continueButton: 'Continuar',
      resendCode: 'Reenviar código en',
      resendNow: 'Reenviar código',
      invalidCode: 'Código de verificación inválido',
      codeExpired: 'El código de verificación ha expirado',
      resendSuccess: 'Código de verificación enviado exitosamente',
    },
    forgotPassword: {
      title: 'Olvidé mi contraseña',
      subtitle: 'Ingresa tu correo electrónico y te enviaremos un enlace para restablecerla',
      emailPlaceholder: 'Correo electrónico',
      sendButton: 'Enviar enlace',
      enterCode: "Ingresar código de verificación",
      emailSent: 'Correo de restablecimiento enviado',
      emailSentDesc: 'Revisa tu correo para las instrucciones de restablecimiento',
    },
    resetPassword: {
      title: 'Nueva contraseña',
      subtitle: 'Crea una contraseña segura y fácil de recordar',
      newPasswordPlaceholder: 'Nueva contraseña',
      confirmPasswordPlaceholder: 'Confirmar contraseña',
      confirmButton: 'Confirmar contraseña',
      passwordUpdated: 'Contraseña actualizada exitosamente',
      invalidToken: 'Token de restablecimiento inválido o expirado',
    },
    validation: {
      emailRequired: 'El correo electrónico es obligatorio',
      emailInvalid: 'Por favor ingresa un correo electrónico válido',
      phoneRequired: 'El número de teléfono es obligatorio',
      phoneInvalid: 'Por favor ingresa un número de teléfono válido',
      passwordRequired: 'La contraseña es obligatoria',
      passwordMin: 'La contraseña debe tener al menos 6 caracteres',
      firstNameRequired: 'El nombre es obligatorio',
      lastNameRequired: 'El apellido es obligatorio',
      confirmPasswordRequired: 'Por favor confirma tu contraseña',
      passwordsNoMatch: 'Las contraseñas no coinciden',
      termsRequired: 'Debes aceptar los términos y condiciones',
      otpRequired: 'El código de verificación es obligatorio',
      otpInvalid: 'Por favor ingresa un código de 4 dígitos válido',
    },
    errors: {
      loginFailed: 'Correo o contraseña incorrectos',
      registerFailed: 'Error al registrar usuario',
      otpFailed: 'Error al verificar el código',
      resetFailed: 'Error al enviar el correo de restablecimiento',
      passwordUpdateFailed: 'Error al actualizar la contraseña',
    },
  },
};

export default Strings; 